server:
  port: 9292
spring:
  application:
    name: consumer-hello

info:
  app:
    name: consumer-hello111
eureka:
  instance:
    hostname: zhent.com #主机名
    prefer-ip-address: true #是否将当前服务的Ip注册到Eureka Server

  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/