server:
  port: 7001
spring:
  application:
    name: eureka-sever
eureka:
  instance:
    hostname: zhent.com #主机名
    prefer-ip-address: true # 是否将当前服务的IP注册到Eureka Server
  client:
    # 是否要注册到其他Eureka Server实列
    register-with-eureka: false
    # 是否要从其他Eureka Server 实列获取数据
    fetch-registry: false
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/