server:
  port: 8001 #当前的EurekaClient服务端口
# 服务注册
info:
  app:
    name: provider-hello111  #当前服务再acruator监控中的应用名称
#    version:1.0.0
spring:
  application:
    name: provider-hello #当前服务注册再Eureka Server的名称
  jpa:
    database: mysql
    show-sql: true
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/test1?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    hikari:
      maximumPoolSize: 15
      max-lifetime: 1800000
      minimum-idle: 2
      idle-timeout: 60000
      connection-timeout: 30000

#
#management:
#  endpoints:
#    web:
#      exposure:
#        include: '*'
#  endpoint:
#    health:
#      show-details:always
#    shutdown:
#      enabled: true
eureka:
  instance:
    hostname: zhent.com #主机名
    profer-ippaddress: true #是否将当前服务的Ip注册到Eureka Server
  client:
    #    fetch-registry: true
    #    register-with-eureka: true
    service-url:
      #      defaultZone: http://localhost:7001/eureka/
      defaultZone: http://${eureka.instance.hostname}:7001/eureka/
